function [fitresult, gof] = GaussianFit1(xgaussian, ygaussian, x, y)
%CREATEFIT1(XGAUSSIAN,YGAUSSIAN)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xgaussian
%      Y Output: ygaussian
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jan-2020 13:05:03


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xgaussian, ygaussian );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
% opts.Display = 'Off';
%opts.Lower = [-Inf -Inf 0];

% opts.Lower = [-2*a -2*a 0];
% opts.Upper = [2*a 2*a 0.5];

% opts.StartPoint = [3244.94113718383 -3.9221260815822 0.171156873513199];
opts.StartPoint = [x(1) y(1) 0.1];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'ygaussian vs. xgaussian', 'Fit result', 'Location', 'NorthEast' );
% Label axes
xlabel('$log(\tau) \ $', 'Interpreter', 'Latex','Fontsize',14)
ylabel('$Rp.G(\tau) \ [\Omega$]','Interpreter', 'Latex','Fontsize',14);
grid on


